"""add payments.invite_message_id

Revision ID: 134ecaca6b3e
Revises: c22f257ef8a1
Create Date: 2026-07-16 17:55:10.032841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134ecaca6b3e'
down_revision: Union[str, Sequence[str], None] = 'c22f257ef8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('invite_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'invite_message_id')
    # ### end Alembic commands ###
