"""add admin tariff limit grace period fields

Revision ID: 1e59482b9621
Revises: 8a1f4c9e2b3d
Create Date: 2026-07-19 03:07:51.920864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e59482b9621'
down_revision: Union[str, Sequence[str], None] = '8a1f4c9e2b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('limit_exceeded_at', sa.Date(), nullable=True))
    op.add_column(
        'admins',
        sa.Column('limit_final_warning_sent', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'limit_final_warning_sent')
    op.drop_column('admins', 'limit_exceeded_at')
    # ### end Alembic commands ###
