"""add channels.welcome_message

Revision ID: 1f52fea30e7f
Revises: 1b352e730e1e
Create Date: 2026-07-16 02:51:20.033719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f52fea30e7f'
down_revision: Union[str, Sequence[str], None] = '1b352e730e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('welcome_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'welcome_message')
    # ### end Alembic commands ###
