"""add chat_type to channels

Revision ID: 346d7d8c5f78
Revises: 1e59482b9621
Create Date: 2026-08-01 04:53:41.027845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '346d7d8c5f78'
down_revision: Union[str, Sequence[str], None] = '1e59482b9621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `ADD COLUMN` orqali yangi enum turi avtomatik yaratilmaydi — avval alohida
    # yaratish kerak. Mavjud `channels` jadvali bo'sh emas — barchasi hozircha
    # kanal, shuning uchun server_default='channel' bilan qo'shiladi.
    chat_type_enum = sa.Enum('channel', 'group', name='chat_type')
    chat_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'channels',
        sa.Column(
            'chat_type',
            chat_type_enum,
            nullable=False,
            server_default='channel',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'chat_type')
    sa.Enum(name='chat_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
