"""add subscriber and payment username full_name

Revision ID: 7d322c596668
Revises: 134ecaca6b3e
Create Date: 2026-07-18 17:28:51.730773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d322c596668'
down_revision: Union[str, Sequence[str], None] = '134ecaca6b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('subscribers', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('subscribers', sa.Column('full_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'full_name')
    op.drop_column('subscribers', 'username')
    op.drop_column('payments', 'full_name')
    op.drop_column('payments', 'username')
    # ### end Alembic commands ###
