"""lifetime subscription plans

Revision ID: 9839314cd81f
Revises: fbf42b1c4889
Create Date: 2026-08-01 05:45:42.953086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9839314cd81f'
down_revision: Union[str, Sequence[str], None] = 'fbf42b1c4889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column(
        'subscription_plans',
        sa.Column('is_lifetime', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('subscription_plans', 'duration_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'duration_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('subscription_plans', 'is_lifetime')
    op.alter_column('subscribers', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
