"""add admin tariff_started_at

Revision ID: fa6097b681b8
Revises: 7d322c596668
Create Date: 2026-07-18 17:58:57.624263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6097b681b8'
down_revision: Union[str, Sequence[str], None] = '7d322c596668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('tariff_started_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'tariff_started_at')
    # ### end Alembic commands ###
