"""admin username, drop limit final warning

Revision ID: fbf42b1c4889
Revises: 346d7d8c5f78
Create Date: 2026-08-01 05:24:10.528264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf42b1c4889'
down_revision: Union[str, Sequence[str], None] = '346d7d8c5f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_column('admins', 'limit_final_warning_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('limit_final_warning_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###
