"""add unique constraint on subscription payment_id

Revision ID: afe8debc8512
Revises: 0616f532b5e2
Create Date: 2026-02-24 02:32:37.939011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe8debc8512'
down_revision: Union[str, Sequence[str], None] = '0616f532b5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_subscription_payment', ['payment_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subscription_payment', type_='unique')

    # ### end Alembic commands ###
